In [2]:
import numpy as np

In [7]:
print(np.__version__) # Ответ на первый вопрос

1.23.3


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('data.csv')

In [6]:
len(df) # Ответ на второй вопрос

11914

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [9]:
df['Model']

0        1 Series M
1          1 Series
2          1 Series
3          1 Series
4          1 Series
            ...    
11909           ZDX
11910           ZDX
11911           ZDX
11912           ZDX
11913        Zephyr
Name: Model, Length: 11914, dtype: object

In [12]:
df.Make.mode()

0    Chevrolet
Name: Make, dtype: object

In [17]:
df.Make.value_counts() # Ответ 3

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [50]:
len(df.loc[df['Make'] == 'Audi']['Model'].unique()) # ОТвет на 4 вопрос

34

In [54]:
df.isnull().any().sum() # Ответ на 5 вопрос

5

In [61]:
mean_of_cylinders = df['Engine Cylinders'].mean()

In [62]:
mean_of_cylinders

5.628828677213059

In [57]:
mode_of_cylinders = df['Engine Cylinders'].mode()

In [58]:
mode_of_cylinders

0    4.0
Name: Engine Cylinders, dtype: float64

In [63]:
df['Engine Cylinders'].fillna(method='ffill').mean()

5.63194561020648

In [60]:
df['Engine Cylinders'].fillna(method='ffill').mode()

0    4.0
Name: Engine Cylinders, dtype: float64

Ответ на 6 вопрос - Да

In [70]:
lotus = df.loc[df['Make'] == 'Lotus']['Engine HP', 'Engine Cylinders']

KeyError: ('Engine HP', 'Engine Cylinders')

In [90]:
x = lotus[['Engine HP', 'Engine Cylinders']].drop_duplicates().to_numpy()

In [91]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [92]:
XTX = x.T.dot(x)

In [97]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [95]:
XTX_inv = np.linalg.inv(XTX)

In [96]:
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [75]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [100]:
w = XTX_inv.dot(x.T).dot(y)

In [101]:
w

array([  4.59494481, -63.56432501])

ОТВЕТ 4.59494481